### ISSUE TITLE
Error in the layout stage

### ISSUE THREAD

**Issue by bistace** [rvaser/ra#1]
Hi,
I tried to use Ra on a Nanopore dataset (in fasta) but it crashes during the layout stage. I tried to launch manually the rala command and got a segmentation fault. Ra is working well on some other datasets, do you have an idea of something I could do to fix this crash ?

**Comment by rvaser** [comment]
Hello,
can you please paste the content of `run.log` here?

Best regards,
Robert

**Comment by bistace** [comment]
Hi,
I have fixed my issue by using fastq files instead of fastas. Anyways, here is the content of the log file when I got the error :

```
[Wed, 14 Mar 18 13:40:49 +0000 FATAL] #2: Could not open file. File path: '/ccc/scratch/cont007/fg0064/fg0064/istaceb/ra/working_directory/longest_consensus_iter0.fasta'.In function: 'OpenFileForBatchLoading'.
[Wed, 14 Mar 18 13:40:49 +0000 FATAL] #2: Could not open file. File path: '/ccc/scratch/cont007/fg0064/fg0064/istaceb/ra/working_directory/longest_consensus_iter0.fasta'.In function: 'OpenFileForBatchLoading'.
Exiting.
```
