### ISSUE TITLE
[suggestion] provide paf in additional to sequence reads

### ISSUE THREAD

**Issue by ishengtsai** [rvaser/ra#10]
Hi,

I am writing to ask if we can provide the Ra the minimap2 paf file in addition to the fastq files? So Ra can skip the alignment stage and get onto the next stages. 

This option would be great because we are running on a server which restrict running time for 96 hours. I think the minimap2 stage can be finished successfully but not sure if the next stages can be done by then.

**Comment by ishengtsai** [comment]
Actually I can just run Rala... nevermind. Thanks!

**Comment by rvaser** [comment]
The current version runs Rala twice though, with a small minimap2 step in between!
