### ISSUE TITLE
Short genome size assembly

### ISSUE THREAD

**Issue by sivico26** [rvaser/ra#12]
Hi Robert, 

I have used Ra for the assembly of a small plant, with ONT and Illumina data. My ONT data is not as long as one would wish, but I am still trying to assemble a draft. Anyway, I tried Ra with both datasets and I got a genome size of 13 Mb, while I am expecting something more close to 280 Mb. 

I would like to know if there are some parameters that I can tweak or something I can do to rerun Ra and get a different assembly than the one I got.

Thanks in advance.

**Comment by rvaser** [comment]
Hello,
what is the average length of your ONT data? Could you copy the command you used to run ra? At the moment there are no command line parameters but you could tweak some of them inside the script.

Best regards,
Robert

**Comment by sivico26** [comment]
Hello again:

Mean read length: 1311 bp
N50: 2065

The command line I used to run Ra was the following:

`ra -t $threads -x ont $ont_reads reads/ngs.fastq.gz > assembly.fasta`

where `$threads` was set to 24 and `$ont_reads` was the path to ont-reads and ngs.fastq.gz are Illumina reads

**Comment by rvaser** [comment]
Hmmm, that looks quite short. Unfortunately, I am not sure if tweaking any parameters will improve Ra assembly with this dataset.

**Comment by sivico26** [comment]
I was able to get a 284 Mb assembly using Flye, quite fragmented as expected. So I think the dataset could give something different than 13 Mb size. Do not you think is worth a try then?

**Comment by rvaser** [comment]
Could you please check what is the average/median contig length of Flye assembly?

**Comment by sivico26** [comment]
I was able to get a 284 Mb assembly using Flye, quite fragmented as expected. So I think the dataset could give something different than 13 Mb size. Do not you think is worth a try then?

**Comment by rvaser** [comment]
Yeah, but what is the average contig length? I have some thresholds on length which might be the cause of  such small ra output.

**Comment by sivico26** [comment]
I did a new assembly with a little bit more of data, and the genome size is 17 Mb now. its N50 is 12133 bp and its average contig length is 12636 bp.

**Comment by rvaser** [comment]
You can try adding parameter `-u` (or `--include-unused`) when running ra (I forgot to update the readme on GitHub with this parameter), but I am not sure if it will help much.

**Comment by sivico26** [comment]
I thought it was just a parameter to also output some intermediate files. I am going to try it and I will be back to you.

**Comment by sivico26** [comment]
Hi again Robert, I tried the `-u` parameter and these are the results I have so far:
```
n	n:500	L50	min	N75	N50	N25	E-size	max	sum	name
1153	1153	434	5501	9909	11589	14859	14021	79092	13.73e6	first_ra/assembly.fasta
1380	1380	494	5825	10211	12133	15878	26471	457699	17.44e6	WGS_ont_only/assembly.fasta
90706	90598	21174	500	2536	4315	7453	6608	459609	314.4e6	WGS_ont_only_u/assembly.fasta
```

The first one is Ra with filtered data and default settings, the second one the same but with unfiltered data and the third is unfiltered with `-u` flag. 

As you suspected it helped with the genome size issue, that order of magnitude makes more sense to me, it is way more fragmented compared with the first two assemblies.

**Comment by rvaser** [comment]
Yeah, your reads are quite short and I am not sure if I can do anything more to increase contiguity :/

**Comment by sivico26** [comment]
All right Robert, thank you for your assistance and for developing Ra!
