### ISSUE TITLE
Ra failed at minimap2 stage

### ISSUE THREAD

**Issue by ishengtsai** [rvaser/ra#6]
Hi,

I am trying to assemble ~60X nanopore data of 1.5Gb genome, but always failed at minimap2 stage. I tried to generate paf/sam file using minimap2 independently outside Ra successfully, so any advices would be appreciated.

Log below:
.
.
[M::worker_pipeline::60395.411*31.30] mapped 52375 sequences
[M::worker_pipeline::60561.059*31.29] mapped 50263 sequences
[M::worker_pipeline::60717.325*31.29] mapped 52061 sequences
[ERROR] failed to write the results
[Ra::run] preconstruction overlap stage

**Comment by rvaser** [comment]
Hello,
it seems that you run out of disk space. Can you please verify that?

Sorry for the delayed response. Best regards,
Robert

**Comment by ishengtsai** [comment]
Yes it's indeed disc space issue, just didn't realise 30T run out so soon.. Thanks.
