### ISSUE TITLE
no option 'p' for rala

### ISSUE THREAD

**Issue by pdimens** [rvaser/ra#9]
Hello, I'm trying to run Ra, however I keep getting an error that the option `p` doesn't exist for `rala` as shown below:

```
[M::main] Version: 2.14-r894-dirty
[M::main] CMD: /bin/minimap2 -t 15 -x ava-pb greysnapper.all.subreads.fasta greysnapper.all.subreads.fasta
[M::main] Real time: 9741.901 sec; CPU: 134577.332 sec; Peak RSS: 40.247 GB
[Ra::run] preconstruction stage
/bin/rala: invalid option -- 'p'
```
The only changes I made to the `Ra` script generated after compilation is changing the paths of `racon` `rala` and `minimap2` to the ones compiled to `/bin/` as shown here:
```python
class Ra:

    __minimap = '/bin/minimap2'
    __rala = '/bin/rala'
    __racon = '/bin/racon'
```
which leads me to believe the issue may be in this section:
```python
     # preconstruction
        eprint('[Ra::run] preconstruction stage')

        rala_params = [Ra.__rala, '-t', str(self.threads)]
        if (self.include_unused):
            rala_params.extend(['-u'])
        rala_params.extend(['-p'])     #right here?
        rala_params.extend([self.tgs_sequences, overlaps])
```

Do you have any information regarding what may be going on?

**Comment by rvaser** [comment]
Hello,
try running `git submodule update --init --recursive` and recompile. Rala version is probably wrong because the parameter `-p` was added recently (it should point to last commit on branch `iterative`).

Best regards,
Robert
